### ISSUE TITLE
Not sure whether this is a Sandwichable problem or a chunk in a globe problem

### ISSUE THREAD

**Issue by Bonono63** [FoundationGames/Sandwichable#10]
I had both chunk in a globe and sandwichable installed, when I went into a globe the game crashed.

Crash Report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 2020-04-26 14:00:42 EDT
Description: Rendering Block Entity

java.lang.NullPointerException
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.15)
    at net.minecraft.client.color.world.BiomeColors.getColor(BiomeColors:14)
    at net.minecraft.client.color.world.BiomeColors.getGrassColor(BiomeColors:18)
    at io.github.foundationgames.sandwichable.SandwichableClient.lambda$onInitializeClient$0(SandwichableClient.java:26)
    at net.minecraft.client.color.block.BlockColors.getColor(BlockColors:112)
    at net.minecraft.client.render.block.BlockRenderManager.renderBlockAsEntity(BlockRenderManager:103)
    at me.modmuss50.dg.globe.GlobeBlockEntityRenderer.renderGlobe(GlobeBlockEntityRenderer.java:89)
    at me.modmuss50.dg.globe.GlobeBlockEntityRenderer.render(GlobeBlockEntityRenderer.java:40)
    at me.modmuss50.dg.globe.GlobeBlockEntityRenderer.render(GlobeBlockEntityRenderer.java:30)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:106)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:95)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:127)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:95)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1207)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:718)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:543)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:989)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.MinecraftClient.handler$znd000$afterCrashHandled(MinecraftClient:7574)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:634)
    at net.minecraft.client.main.Main.main(Main:204)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: globedimension:globe // me.modmuss50.dg.globe.GlobeBlockEntity
  Block: Block{globedimension:globe}
  Block location: World: (8,128,8), Chunk: (at 8,8,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Block: Block{globedimension:globe}
  Block location: World: (8,128,8), Chunk: (at 8,8,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Block Entity NBT: {return_dim:"minecraft:overworld",base_block:"minecraft:diamond_ore",globe_id:0,return_z:-10,x:8,return_y:98,y:128,return_x:75,z:8,id:"globedimension:globe"}

-- Affected level --
  All players: 1 total; [class_746['Mr_Bonito'/112410, l='MpServer', x=8.50, y=129.00, z=8.50]]
  Chunk stats: Client Chunk Cache: 441, 57
  Level dimension: globedimension:globe
  Level name: MpServer
  Level seed: 4191195301238277406
  Level generator: ID 09 - simplex, ver 0. Features enabled: false
  Level generator options: {}
  Level spawn location: World: (0,91,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 19599 game time, 19599 day time
  Known server brands: 
  Level was modded: false
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_232, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode),
  Memory: 1986352536 bytes (1894 MB) / 3247964160 bytes (3097 MB) up to 5779226624 bytes (5511 MB)
  CPUs: 12
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6200m
  Suspected Mods: Chunk In A Globe (globedimension), Fabric Loader (fabricloader), Sandwichable (sandwichable)
  Fabric Mods: amecs: Amecs 1.2.9+1.15-pre5
               appleskin: AppleSkin 1.0.8
               aquarius: Aquarius 1.4.0+1.15
               authme: Auth Me 1.1.1
               autoconfig1u: Auto Config v1 Updated 2.0.1
               berrysmod: Berry's Mod 1.2.0.1
               better_wither_skeletons: Better Wither Skeletons 1.0.0
               betterdroppeditems: Better Dropped Items 1.0.1
               biom4st3rportal: Fancy Fountain Passage 2.0.1
               biow0rks: biow0rk5 0.4.4
               blue_endless_jankson: jankson +
               cardinal-components-base: Cardinal Components API 2.3.4
               cardinal-components-entity: Cardinal Components API 2.3.4
               chestlatchfixer: ChestLatchFixer 1.1.0
               clear-skies: Clear Skies 1.1.19
               clipboards: Clipboards 1.0.0+1.15.2
               cloth: Cloth Events 1.2.0
               cloth-basic-math: Cloth Basic Math 0.4.1
               cloth-config2: Cloth Config v2 2.13.2
               coderecipes: Programmatic Recipes 0.2.3
               com_moandjiezana_toml_toml4j: toml4j 0.7.2
               cotton: Cotton 1.0.3
               cotton-cauldron: Cotton Cauldron 1.0.3
               cotton-commons: Cotton Commons 1.0.0-rc.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.1
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               couplings: Couplings 1.3.1
               curses: Curses 1.2.0
               dark-loading-screen: Dark Loading Screen 1.2.0
               darkness: True Darkness 1.3.18
               dataloader: Data Loader 2.0.0+mc1.15.2
               enchantedtooltips: Enchanted ToolTips 1.2.4
               extradoors: ExtraDoors 1.8.0-1.15
               extrashields: Extra Shields 0.2.0+1.15.2
               fabric: Fabric API 0.7.1+build.301-1.15
               fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+e40501d40c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
               fabric-furnaces: Fabric Furnaces 1.2.0
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
               fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+ec951ea40c
               fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b395
               fabric-start-the-music: Start the Music! 0.1.1
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
               fabriccontrolling: Fabric Controlling 1.0.1
               fabricloader: Fabric Loader 0.8.2+build.194
               flonters: Flonters 1.0.2+1.15.1
               ftc: Fabric Title Changer 1.0.2
               gbfabrictools: GBfabrictools 1.1.0
               globedimension: Chunk In A Globe 1.15.2-1.0.2
               glowingbeds: Glowing Beds 1.0.2
               healthoverlay: Health Overlay 2.3.10
               iamverysmart: I Am Very Smart 2.0.0+mc1.15.2
               imbuedtorches: Imbued Torches 1.1.0
               inventorysorter: Inventory Sorter 1.6.4
               jankson: Jankson 2.0.1+j1.2.0
               kayak: kayak 0.1.1.22
               kirin: Kirin UI 1.5.2-1.15.2-SNAPSHOT
               kyrptconfig: Kytpt Config 1.0.0
               leveluphp: Level Up HP 5.0.0+mc1.15.2
               libcd: LibCapableData 2.2.2+1.15.2
               libgui: LibGui 1.6.0
               lithium: Lithium 0.4.6
               loadcatcher: Entrypoint Catcher 1.1.0
               malilib: MaLiLib 0.10.0-dev.20+arne.6
               mambience: MAmbience 1.1.0
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               me_zeroeightsix_fiber: fiber 0.12.0-5
               minecraft: Minecraft 1.15.2
               minihud: MiniHUD 0.19.0-dev.20200121.203515
               mm: Manningham Mills 2.0
               mobjar: mob.jar 1.0.1+1.15.2
               mobz: MobZ 2.2.1
               modmenu: Mod Menu 1.10.2+build.32
               modpackmenu: Modpack Menu 1.15.2-1.0.0
               moenchantments: Mo'Enchantments 1.9.6
               moretotems: More Totems 1.0.0
               namepain: Name Pain 1.2.2
               nicetohave: Nice to Have 1.3.0-beta.5
               notenoughcrashes: Not Enough Crashes 1.2.3+1.15.1
               okzoomer: Ok Zoomer 2.1.4-1.15.2
               org_aeonbits_owner_owner: owner 1.0.8
               org_jetbrains_annotations: annotations 18.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
               overgrowncities: Overgrown Cities 0.1.0
               pconfig: Paradox Config 0.3.3-alpha
               permafrost: Permafrost 1.3.1+1.15.1
               phosphor: Phosphor 0.5.2+build.6
               playerlightfix: Player Light Fix 1.0.1
               pling: Pling 1.1.0
               presencefootsteps: Presence Footsteps r24+1.15.2
               programmerartinjector: Programmer Art Injector 1.1.2
               rare-ice: Rare Ice 0.1.6
               rotmgfood: Rotmg Food 1.1.0
               roughlyenoughitems: Roughly Enough Items 3.6.13
               roughlyenoughresources: Roughly Enough Resources 1.3.2
               sandwichable: Sandwichable 1.0.2
               simplexterrain: Simplex Terrain 0.5.1
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 2.4.1
               snowdrift: Snowdrift ${version}
               spinnery: Spinnery 2.0.0+fabric-20w06a
               stepup: StepUp 11.14-fabric0.2.7-1.0.2
               straightenup: Straighten Up 1.0.0
               sweettooth: Sweet Tooth 1.1.2
               tooltipped: Tooltipped 1.1
               tooltipwrap: Tooltip Autowrap 1.0.2
               torohealth: ToroHealth Damage Indicators 1.15.1-fabric-1
               trees-do-not-float: Trees Do Not Float 1.8.69
               vanilla-toolsets: Vanilla Toolsets 1.2.2
               walljump: Wall-Jump! 1.3.3+1.15
  Launched Version: MultiMC5
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  CPU: 12x AMD Ryzen 5 2600 Six-Core Processor
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by FoundationGames** [comment]
Funny, you seem to be playing AOF. I have used Chunk in a Globe with Sandwichable and there is not usually an issue with entering a globe... Is there, by any chance, a shrub nearby the globe when you enter?

**Comment by Bonono63** [comment]
I was playing a mod pack I made with mods I collected from curse forge myself, and while testing I decided to play around with chunk in a globe. I'm not entirely sure why, but the game crashed every time I went into the globe, I have too many crashes installed and it said an incompatibility between chunk in a globe and sandwichables was the problem. I was in a forest biome and I don't think there where any shrubs nearby.

**Comment by FoundationGames** [comment]
There was likely a shrub nearby, they hide in the foliage pretty well. Shrubs and potted shrubs are the only blocks in Sandwichable that use foliage colors. My guess is that when the "Globe dimension" you enter when entering a globe was trying to render that shrub in the background but ran into an error, I recommend posting this issue on Chunk In a Globe's issue tracker as well. I will leave this issue open since it might be an issue on Sandwichable's part, but it's most likely Chunk in a Globe.

**Comment by Bonono63** [comment]
Ok thanks, I'll look back into it. Your mod is pretty cool and i wanted understand what was going on between the mods that caused the error.
