### ISSUE TITLE
Incompatible with optfabric in 1.18.2

### ISSUE THREAD

**Issue by lisirrx** [FoundationGames/Sandwichable#133]
HI, I used sandwichable 1.2+1.18.2 together with optfabric 1.13.0.
And throw an error like
```
Caused by: java.lang.IllegalStateException: Cannot find shim method renderSandwichGui(Lnet/minecraft/class_1799;Lnet/minecraft/class_809$class_811;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in io/github/foundationgames/sandwichable/mixin/BuiltinModelItemRendererMixin
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.lambda$postApply$2(InterceptingMixinPlugin.java:131) ~[optifabric-1.13.0.jar:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at me.modmuss50.optifabric.compat.InterceptingMixinPlugin.postApply(InterceptingMixinPlugin.java:127) ~[optifabric-1.13.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.postApply(PluginHandle.java:189) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.postApply(MixinInfo.java:1372) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1276) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	... 19 more
```

I have tried to fix this in optfabric by replacing `me.modmuss50.optifabric.compat.sandwichable.mixin.BuiltinModelItemRendererMixin$renderSandwichGui` to `sandwichable$renderSandwichGui`
and it works. 
Is this right way to fix this problem?

**Comment by FoundationGames** [comment]
Yes, that is an optifabric problem, not mine
Please see https://lambdaurora.dev/optifine_alternatives/ for better ways to get optifine features with fabric

**Comment by lisirrx** [comment]
> Yes, that is an optifabric problem, not mine Please see https://lambdaurora.dev/optifine_alternatives/ for better ways to get optifine features with fabric

ok, thanks for your reply~, and your mod too~

**Comment by Redd56** [comment]
If you want specifics lisirrix. I personaly use sodium with iris(shaders), indium, sodium extras, lambda better grass, reese's sodium options, smooth boot, and starlight all together. All great mods for performance. Theres a few others i need to add to my stack like continuity (connective textures) and lithium (i forgor what it does)
Lamb dynamic lights also is good but i was seeing problems with bad lighting lag a while back. The big may have been fixed since though
