### ISSUE TITLE
Server Crash on start

### ISSUE THREAD

**Issue by Bonono63** [FoundationGames/Sandwichable#19]
I started my server and it crashed immediately.

Log:
[10:51:19] [main/INFO]: Loading for game Minecraft 1.15.2
[10:51:23] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-resource-loader-v0: used 0.1.10+06c939b395, also found 0.1.10+06c939b30c
 - Conflicting versions found for fabric-item-groups-v0: used 0.1.6+ec40b2e10c, also found 0.1.6+045efb460c
 - Conflicting versions found for fabric-climbable-api-v1: used 1.0.0+e40501d40c, also found 1.0.0+6ffe71e20c
[10:51:23] [main/WARN]: Mod `everythingisahat` (1.0.4) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/WARN]: Mod `spelunkers` (1.0.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/WARN]: Mod `clear-skies` (1.1.19) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/WARN]: Mod `biom4st3rportal` (2.0.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/WARN]: Mod `armordisguise` (1.0.2) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/WARN]: Mod `betterdroppeditems` (1.0.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[10:51:23] [main/INFO]: [FabricLoader] Loading 173 mods: fabric-keybindings-v0@0.1.1+dfdb52d60c, couplings@1.3.1, logicalrecipes@1.0.0, notenoughcrashes@1.2.3+1.15.1, no-potion-offset@1.0.0, step-height-entity-attribute@1.0.0, fabricloader@0.8.4+build.198, trinkets@2.4.2, survivalisland@0.1.0, satin@1.4.0-nightly.19w46b+build.1, artifice@0.6.1+1.15.2, riverredux@0.1.1, healthoverlay@2.3.10, fabric-dimensions-v1@0.3.0+2ad156310c, fabric-api-base@0.1.2+b7f9825d0c, darkness@1.3.18, chatcalc@2.1, fabric-start-the-music@0.1.1, namepain@1.2.2, roughlyenoughresources@1.3.2, chestlatchfixer@1.1.0, org_jetbrains_kotlin_kotlin-stdlib@1.3.71, everythingisahat@1.0.4, iamverysmart@2.0.0+mc1.15.2, com_moandjiezana_toml_toml4j@0.7.2, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, leveluphp@5.0.0+mc1.15.2, imbuedtorches@1.1.0, berrysmod@1.2.0.1, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.71, minihud@0.19.0-dev.20200121.203515, permafrost@1.3.1+1.15.1, spelunkers@1.0.0, fabric@0.7.1+build.301-1.15, bunch-o-trinkets@1.0.0, fabric-networking-v0@0.1.7+003643510c, pufferfishcronch@1.0.0, pling@1.1.0, org_codehaus_groovy_groovy@3.0.3, cotton-config@1.0.0-rc.7, resourcepackorganizer@1.1.0-Fabric, modpackmenu@1.15.2-1.0.0, clipboards@1.0.0+1.15.2, tk_valoeghese_zoesteriaconfig@1.2.0, suppressunknownitem@2.0.1+mc1.15.2, modmenu@1.10.2+build.32, dataloader@2.0.0+mc1.15.2, coderecipes@0.2.3, blur@1.0.5, grass_kiss@0.2.2, phosphor@0.5.2+build.6, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.71, fabric-tool-attribute-api-v1@1.1.0+3e5587510c, rare-ice@0.1.6, org_aeonbits_owner_owner@1.0.8, mobjar@1.0.1+1.15.2, fabric-biomes-v1@0.1.5+3b05f68e0c, ftc@1.0.2, fabric-events-interaction-v0@0.3.0+fac69e320c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, loadcatcher@1.1.0, fabric-language-kotlin@1.3.71+build.1, kayak@0.1.1.22, cloth-config2@2.14.0, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.5, amecs@1.2.9+1.15-pre5, fabric-resource-loader-v0@0.1.10+06c939b395, malilib@0.10.0-dev.20+arne.6, org_jetbrains_kotlin_kotlin-reflect@1.3.71, immersivelighting@2.0.1F, programmerartinjector@1.1.2, clear-skies@1.1.19, cardinal-components-entity@2.3.5-alt, playerlightfix@1.0.1, biom4st3rportal@2.0.1, libblockattributes_fluids@0.6.6, authme@1.1.1, fabric-commands-v0@0.2.0+2e0c4ff50c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, cardinal-components-base@2.3.5-alt, blast@1.1.1, fabric-mining-levels-v0@0.1.2+ec951ea40c, cotton-player-events@1.0.2, sheepconsistency@1.0.1, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, bettermineshafts@0.4.1, org_jetbrains_annotations@19.0.0, craftpresence@1.6.5, fabric-renderer-api-v1@0.2.10+f08b61330c, parchment@1.0.1+1.15.2, gbfabrictools@1.2.1.1.15, inventorysorter@1.6.4, mambience@1.1.0, cotton@1.0.3, tooltipped@1.1, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.5, skyworld@0.3.0-pre-release, moenchantments@1.9.6, fabric-containers-v0@0.1.3+b7f9825d0c, lithium@0.4.6, fabric-object-builder-api-v1@1.1.0+3e5587510c, glowingbeds@1.0.2, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, hardcorequesting@0.1.1-SNAPSHOT, mm@2.0, extradoors@1.8.0-1.15, fabric-textures-v0@1.0.4+821cdba70c, infgen@1.3.1, sandwichable@1.1, titlescreennotice@1.15.2-0.0.1, wolveswitharmor@1.1.0, stepup@11.14-fabric0.2.7-1.0.2, fabric-rendering-fluids-v1@0.1.6+12515ed90c, reach-entity-attributes@1.0.0, trees-do-not-float@1.8.69, cotton-logging@1.0.0-rc.4, simplexterrain@0.5.1, walljump@1.3.3+1.15, classicombat@1.0-SNAPSHOT, sodium@0.1.0-SNAPSHOT, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, biow0rks@0.4.4, curses@1.2.0, fabric-particles-v1@0.1.2+ad2f81bd0c, libblockattributes_core@0.6.6, wildworld@1.2.0+1.15, cloth@1.2.0, minecraft@1.15.2, fabric-networking-blockentity-v0@0.2.3+e08a73050c, okzoomer@2.1.4-1.15.2, boringbackgrounds@1.0.1, jankson@2.0.1+j1.2.0, cloth-basic-math@0.5.0, rotmgfood@1.1.0, fabric-command-api-v1@1.0.2+2aebb7ff0c, armordisguise@1.0.2, tooltipwrap@1.0.2, cotton-commons@1.0.0-rc.4, easiercrafting@1.15-fabric0.4.23-1.6.1.beta2, betterdroppeditems@1.0.1, fabric-renderer-indigo@0.2.23+9290e2ed0c, spinnery@2.0.0+fabric-20w06a, advancements-enlarger@1.0.0, dark-loading-screen@1.2.0, cotton-datapack@1.0.1, roughlyenoughitems@3.6.17, kyrptconfig@1.0.0, libgui@1.6.0, slight-gui-modifications@0.4.1, sweettooth@1.1.2, fabric-rendering-v0@1.1.0+534104900c, vanilla-toolsets@1.2.2, fabric-rendering-v1@1.0.0+2a034f0a0c, smoothscrollingeverywhere@2.4.1, autoconfig1u@2.2.0, me_zeroeightsix_fiber@0.12.0-5, fabric-content-registries-v0@0.1.3+b7f9825d0c, straightenup@1.0.0, fabric-tag-extensions-v0@0.1.3+abd915800c, blue_endless_jankson@+, fabric-furnaces@1.2.0, appleskin@1.0.8, enchantedtooltips@1.2.4, kirin@1.5.2-1.15.2-SNAPSHOT, fabric-climbable-api-v1@1.0.0+e40501d40c, aquarius@1.4.0+1.15, fabric-events-lifecycle-v0@0.1.2+003643510c, org_codehaus_groovy_groovy-jsr223@3.0.3, better_wither_skeletons@1.0.0, fabric-object-builders-v0@0.5.1+3e5587510c, presencefootsteps@r24+1.15.2
[10:51:23] [main/WARN]: Mod `berrysmod` (1.2.0.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[10:51:23] [main/WARN]: Mod `kayak` (0.1.1.22) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[10:51:23] [main/WARN]: Mod `immersivelighting` (2.0.1F) does not respect SemVer - comparison support is limited.
[10:51:23] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[10:51:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/E:/Minecraft%20Servers/FUCKS%20beta%20Server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[10:51:27] [main/WARN]: Error loading class: net/minecraft/class_1132 (java.lang.ClassNotFoundException: net/minecraft/class_1132)
[10:51:27] [main/WARN]: @Mixin target net.minecraft.class_1132 was not found notenoughcrashes.mixins.json:MixinIntegratedServer
[10:51:27] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[10:51:27] [main/WARN]: @Mixin target net.minecraft.class_634 was not found me.andre111.mambience.fabric.mixin.json:MixinClientPlayNetworkHandler
[10:51:27] [main/WARN]: Error loading class: net/minecraft/class_3799 (java.lang.ClassNotFoundException: net/minecraft/class_3799)
[10:51:27] [main/WARN]: @Mixin target net.minecraft.class_3799 was not found me.andre111.mambience.fabric.mixin.json:MixinMinecraftClientGame
[10:51:27] [main/FATAL]: Mixin prepare failed preparing BuiltinModelItemRendererMixin in sandwichable.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class io.github.foundationgames.sandwichable.mixin.BuiltinModelItemRendererMixin in environment type SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class io.github.foundationgames.sandwichable.mixin.BuiltinModelItemRendererMixin in environment type SERVER
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:515) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:440) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:416) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_232]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:190) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class io.github.foundationgames.sandwichable.mixin.BuiltinModelItemRendererMixin in environment type SERVER
	at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:76) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.getClassByteArray(Knot.java:208) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:47) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:63) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1295) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848) ~[fabric-server-launch.jar:?]
	... 22 more

**Comment by FoundationGames** [comment]
Bit strange since I have seen Sandwichable run on servers, but I believe I know how to fix it.

**Comment by Bonono63** [comment]
I think its a incompatibility between another mod, not sure.

**Comment by FoundationGames** [comment]
Fixed in 1.1.1, it was not compat.
